### ISSUE TITLE
No possibility to adjust markup in SuggestionList component

### ISSUE THREAD

**Issue by DanielRuf** [shopgate/theme-gmd#461]
Currently it is not possibly to add more markup to a SuggestionList component (only title of product / string), only a string which is rendered as-is. React escapes the string. Maybe some portals might be useful there. And some way to allow rendering HTML.

https://github.com/shopgate/theme-gmd/blob/19e981a97972b71c4d73d24de7bd2d7fb42a9044/components/Search/components/Suggestions/components/List/index.jsx#L48

**Comment by dgrebe-shopgate** [comment]
We will add portals for this in the Engage release 6.7.0
